import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildFixtures } from '../fixtures/lib/catalog';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'fixtures', 'generated');
const check = process.argv.includes('--check');

const specs = buildFixtures();
const manifest = specs.map((s) => ({
  file: s.file,
  bytes: s.bytes.length,
  sha256: createHash('sha256').update(s.bytes).digest('hex'),
  description: s.description,
}));
const manifestText = JSON.stringify({ note: 'Synthetic fixtures. Generated by `npm run fixtures`. Hashes identify bytes only.', fixtures: manifest }, null, 2) + '\n';

if (check) {
  let bad = 0;
  for (const s of specs) {
    const p = join(dir, s.file);
    if (!existsSync(p) || !Buffer.from(s.bytes).equals(readFileSync(p))) {
      console.error(`DIFFERS: ${s.file}`);
      bad++;
    }
  }
  const known = new Set(specs.map((s) => s.file).concat(['MANIFEST.json']));
  for (const f of readdirSync(dir)) if (!known.has(f)) { console.error(`UNEXPECTED: ${f}`); bad++; }
  if (!existsSync(join(dir, 'MANIFEST.json')) || readFileSync(join(dir, 'MANIFEST.json'), 'utf8') !== manifestText) {
    console.error('DIFFERS: MANIFEST.json');
    bad++;
  }
  if (bad) process.exit(1);
  console.log(`fixtures OK: ${specs.length} files match the generator`);
} else {
  mkdirSync(dir, { recursive: true });
  for (const s of specs) writeFileSync(join(dir, s.file), s.bytes);
  writeFileSync(join(dir, 'MANIFEST.json'), manifestText);
  console.log(`wrote ${specs.length} fixtures to fixtures/generated`);
}
